Stringable java classes support
RTBHOUSE/avro-fastserde pull request #5
Opened 2018-05-17 09:54 UTC by dervan

I've introduced Stringable classes support. In relation to that, I did some additional refactor with SchemaMapper - I think it significantly simplified schema classes handling in code.

2018-05-21 20:46 UTC, flowenol requested changes

2018-05-21 20:46 UTC, flowenol commented on src/main/java/com/rtbhouse/utils/avro/FastDeserializerGenerator.java
> +import com.sun.codemodel.*;
We don't want wildcarded import statements. Please fix your IDE not to wrap imports.

2018-05-21 20:46 UTC, flowenol commented on src/main/java/com/rtbhouse/utils/avro/FastDeserializerGenerator.java
> +            JCatchBlock catchBlock = tryDeserializeBlock._catch(codeModel.ref(Throwable.class));
I recommend removing this try block completely. We are already declaring in the method signature that we may throw an IOException, which in fact can be only produced by Decoder methods. In this case, any other exception different than IOException comes from badly generated code, let's not confuse this with IO related errors.

2018-05-21 20:46 UTC, flowenol commented on src/main/java/com/rtbhouse/utils/avro/FastDeserializerGenerator.java
> +                for (char b : defaultValue.getTextValue().toCharArray()) {
I'm not sure if we can assume that we will always encounter text value here, I think that processing raw bytes would be safer. Or you can distinguish between bytes and text using isBinary on JsonNode.

2018-05-21 20:46 UTC, flowenol commented on src/main/java/com/rtbhouse/utils/avro/FastDeserializerGenerator.java
> +                for (byte b : defaultValue.getTextValue().getBytes()) {
As above.

2018-05-21 20:46 UTC, flowenol commented on src/main/java/com/rtbhouse/utils/avro/FastDeserializerGenerator.java
> +        method._throws(Throwable.class);
Why would we need to throw that? As above, isn't the IOException sufficient?

2018-05-21 20:46 UTC, flowenol commented on src/main/java/com/rtbhouse/utils/avro/SchemaMapper.java
> +class SchemaMapper {
I don't like the name of this class. It's more like a SchemaHelper, because it handles many schema-related tasks, not only schema to JClass mappings. Good refactor though, saves a lot of LOC in both serializer and deserializer.

2018-05-21 20:46 UTC, flowenol commented on src/main/java/com/rtbhouse/utils/avro/SchemaMapper.java
> +    public static boolean haveStringableKey(Schema schema) {
You mean: hasStringableKey?

2018-05-21 20:46 UTC, flowenol commented on src/main/java/com/rtbhouse/utils/avro/SchemaMapper.java
> +            throw new SchemaMapperException("String schema expected!");
You mean: Map schema expected?

2018-05-21 20:46 UTC, flowenol commented on src/main/java/com/rtbhouse/utils/avro/SchemaMapper.java
> +        return schema.getProp("java-class") != null;
SpecificData.CLASS_PROP - use this

2018-05-21 20:46 UTC, flowenol commented on src/main/java/com/rtbhouse/utils/avro/SchemaMapper.java
> +        return schema.getProp("java-key-class") != null;
SpecificData.KEY_CLASS_PROP - use this

2018-05-21 20:46 UTC, flowenol commented on src/main/java/com/rtbhouse/utils/avro/SchemaMapper.java
> +}
And what about stringable elements in arrays (SpecificData.ELEMENT_PROP)?

2018-05-21 20:46 UTC, flowenol commented on src/main/java/com/rtbhouse/utils/avro/FastSerializerGenerator.java
> +            serializeMethod.annotate(SuppressWarnings.class).param("value", "unchecked");
This suppression is really ugly and should be avoided. What causes such warnings? Can it be fixed in a proper way?

2018-05-21 20:46 UTC, flowenol commented on src/main/java/com/rtbhouse/utils/avro/FastSerializerGenerator.java
>      private boolean doesNotContainMethod(final Schema schema) {
Please sync the naming with deserializer - you renamed the similar method over there.

2018-05-21 20:46 UTC, flowenol commented on src/main/java/com/rtbhouse/utils/avro/FastDeserializerGenerator.java
> +            return JExpr._null();
Why null in similar methods for Fixed and Enum and JExpr._null() here? Please explain or make it stricter.

2018-05-21 22:24 UTC, flowenol requested changes

2018-05-21 22:24 UTC, flowenol commented on src/main/java/com/rtbhouse/utils/avro/SchemaMapper.java
> +    SchemaMapper(JCodeModel codeModel, boolean useGenericTypes) {
I do not encourage to use package access modifier, public is ok - this applies everywhere.

2018-05-22 15:27 UTC, dervan commented on src/main/java/com/rtbhouse/utils/avro/FastDeserializerGenerator.java
> +                for (char b : defaultValue.getTextValue().toCharArray()) {
According to avro specification: "Default values for bytes and fixed fields are JSON strings, where Unicode code points 0-255 are mapped to unsigned 8-bit byte values 0-255."

2018-05-23 11:27 UTC, dervan commented on src/main/java/com/rtbhouse/utils/avro/SchemaMapper.java
> +}
They are handled by defining "java-class" property in "items" schema. Same method is described https://issues.apache.org/jira/browse/AVRO-1268 .
Note also, that it seems that SpecificData.ELEMENT_PROP is not used in SpecificDatumReader neither SpecificCompiler.java, so I guess that this is just for ReflectData use.

2018-05-23 11:27 UTC, dervan commented
I hope I  addressed your concerns. Necessary exceptions from stringable classes are handled more subtle now. Rest of requests are either implemented or explained.

2018-05-25 10:00 UTC, flowenol commented on src/main/java/com/rtbhouse/utils/avro/FastDeserializerGenerator.java
> +            JBlock topLevelDeserializeBlock = new JBlock();
Consider following code:

```
            JMethod deserializeMethod = deserializerClass.method(JMod.PUBLIC, readerSchemaClass, "deserialize");

            JBlock topLevelDeserializeBlock = new JBlock();
            JVar result = declareValueVar("result", aliasedWriterSchema, topLevelDeserializeBlock);

            switch (aliasedWriterSchema.getType()) {
            case RECORD:
                processRecord(readerSchemaVar, result, aliasedWriterSchema, reader, topLevelDeserializeBlock,
                        fieldAction);
                break;
            case ARRAY:
                processArray(readerSchemaVar, result, null, aliasedWriterSchema, reader, topLevelDeserializeBlock,
                        fieldAction);
                break;
            case MAP:
                processMap(readerSchemaVar, result, null, aliasedWriterSchema, reader, topLevelDeserializeBlock,
                        fieldAction);
                break;
            default:
                throw new FastDeserializerGeneratorException(
                        "Incorrect top-level writer schema: " + aliasedWriterSchema.getType());
            }

            if (schemaAssistant.getExceptionsFromStringable().isEmpty()) {
                assignBodyBlock(deserializeMethod, topLevelDeserializeBlock);
            } else {
                JTryBlock tryBlock = deserializeMethod.body()._try();

                assignBodyBlock(tryBlock, topLevelDeserializeBlock);
                for (Class<? extends Exception> classException : schemaAssistant.getExceptionsFromStringable()) {
                    JCatchBlock catchBlock = tryBlock._catch(codeModel.ref(classException));
                    JVar exceptionVar = catchBlock.param("e");
                    catchBlock.body()._throw(JExpr._new(codeModel.ref(AvroRuntimeException.class)).arg(exceptionVar));
                }
            }

            deserializeMethod._throws(codeModel.ref(IOException.class));
            deserializeMethod.param(Decoder.class, DECODER);

            topLevelDeserializeBlock._return(result);
```

This allows omitting unwanted braces introduced by JBlock at topLevelDesrializeBlock.
assignBodyBlock in FastDeserializerGeneratorBase would look like this:

```
protected static void assignBodyBlock(Object statement, JBlock body) {
        try {
            Field field = statement.getClass().getDeclaredField("body");

            field.setAccessible(true);
            field.set(statement, body);
            field.setAccessible(false);

        } catch (ReflectiveOperationException e) {
            throw new FastDeserializerGeneratorException(e);
        }
    }
```

2018-05-30 04:37 UTC, flowenol approved these changes

2018-05-30 04:40 UTC, merged